version: '3.3'
services:
  homeassistant:
    container_name: homeassistant
    image: 'lscr.io/linuxserver/homeassistant:latest'
    network_mode: 'host'
    volumes:
    - homeassistant:/config
    environment:
    - PGID=1000
    - PUID=1000
    - TZ=Europe/Stockholm
    ports:
    - 8123:8123
    restart: unless-stopped
  node-red:
    container_name: node-red
    image: 'nodered/node-red:latest'
    volumes:
    - node-red:/data
    environment:
    - TZ=Europe/Stockholm
    ports:
    - 1880:1880
    restart: unless-stopped
volumes:
  homeassistant:
    name: homeassistant
    driver: local
    external: false
  node-red:
    name: node-red
    driver: local
    external: false
