version: '3.3'
services:
    uptime-kuma:
        container_name: uptime-kuma
        image: 'louislam/uptime-kuma:latest'
        ports:
        - '3001:3001'
        volumes:
        - 'uptime-kuma:/app/data'
        environment:
        - 'TZ=Europe/Stockholm'
        restart: unless-stopped
volumes:
    uptime-kuma:
        name: uptime-kuma
        driver: local