version: '3.3'
services:
    homer:
        container_name: homer
        image: 'b4bz/homer:latest'
        ports:
        - '83:8080'
        volumes:
        - 'homer:/www/assets'
        restart: unless-stopped
    flame:
        container_name: flame
        image: 'pawelmalak/flame:latest'
        ports:
        - 5005:5005
        volumes:
        - flame:/app/data
        - /var/run/docker.sock:/var/run/docker.sock
        environment:
        - PASSWORD=${flame_PASSWORD}
        restart: unless-stopped
volumes:
    homer:
        name: homer
        driver: local
    flame:
        name: flame
        driver: local
