version: '3.3'
services:
  flame:
    container_name: flame
    image: 'pawelmalak/flame:latest'
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - flame:/app/data
    environment:
    - PASSWORD=${flame_PASSWORD}
    ports:
    - 5005:5005
    restart: unless-stopped
  homer:
    container_name: homer
    image: 'b4bz/homer:latest'
    volumes:
    - homer:/www/assets
    ports:
    - 83:8080
    restart: unless-stopped
volumes:
  flame:
    name: flame
    driver: local
    external: false
  homer:
    name: homer
    driver: local
    external: false
