version: '3.3'
services:
    portainer:
        container_name: portainer
        image: 'portainer/portainer-ee:latest'
        ports:
        - '9443:9443'
        volumes:
        - 'portainer_data:/data'
        - '/var/run/docker.sock:/var/run/docker.sock'
        restart: always
    openldap:
        container_name: openldap
        image: 'osixia/openldap:latest'
        ports:
        - '389:389'
        - '636:636'
        environment:
        - 'LDAP_ORGANISATION=${openldap_LDAP_ORGANISATION}'
        - 'LDAP_DOMAIN=${openldap_LDAP_DOMAIN}'
        - 'LDAP_ADMIN_PASSWORD=${openldap_LDAP_ADMIN_PASSWORD}'
        restart: always
volumes:
    portainer_data:
        name: portainer_data
        driver: local
