version: '3.3'
services:
  openldap:
    container_name: openldap
    image: 'osixia/openldap:latest'
    environment:
    - LDAP_ADMIN_PASSWORD=${openldap_LDAP_ADMIN_PASSWORD}
    - LDAP_DOMAIN=${openldap_LDAP_DOMAIN}
    - LDAP_ORGANISATION=${openldap_LDAP_ORGANISATION}
    ports:
    - 389:389
    - 636:636
    restart: always
  portainer:
    container_name: portainer
    image: 'portainer/portainer-ee:latest'
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - portainer_data:/data
    ports:
    - 9443:9443
    restart: always
volumes:
  portainer_data:
    name: portainer_data
    driver: local
    external: false
