version: '3.3'
services:
    openldap:
        container_name: openldap
        image: 'osixia/openldap:latest'
        ports:
        - '389:389'
        - '636:636'
        environment:
        - 'LDAP_ORGANISATION=${openldap_LDAP_ORGANISATION}'
        - 'LDAP_DOMAIN=${openldap_LDAP_DOMAIN}'
        - 'LDAP_ADMIN_PASSWORD=${openldap_LDAP_ADMIN_PASSWORD}'
        restart: always