version: '3.3'
services:
  openldap:
    container_name: openldap
    image: 'osixia/openldap:latest'
    environment:
    - LDAP_ADMIN_PASSWORD=${openldap_LDAP_ADMIN_PASSWORD}
    - LDAP_DOMAIN=${openldap_LDAP_DOMAIN}
    - LDAP_ORGANISATION=${openldap_LDAP_ORGANISATION}
    ports:
    - 389:389
    - 636:636
    restart: always
