version: '3.3'
services:
    portainer:
        container_name: portainer
        image: 'portainer/portainer-ee:latest'
        ports:
        - '9443:9443'
        volumes:
        - 'portainer_data:/data'
        - '/var/run/docker.sock:/var/run/docker.sock'
        restart: always
volumes:
    portainer_data:
        name: portainer_data
        driver: local
