version: '3.3'
services:
  portainer:
    container_name: portainer
    image: 'portainer/portainer-ee:latest'
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - portainer_data:/data
    ports:
    - 9443:9443
    restart: always
volumes:
  portainer_data:
    name: portainer_data
    driver: local
    external: false
